Repository DevCycleHQ/test-harness, pull requests merged in 2022-12, with the labels that each got.

#61 fix: update to send 201 on POST `/:location` call
  proxies/nodejs/handlers/location.ts
Labels: 1 min review

#58 Dvc 5412 close clients
  harness/features/allFeatures.local.test.ts
  harness/features/allVariables.local.test.ts
  harness/features/initialize.local.test.ts
  harness/features/track.local.test.ts
  harness/features/variable.local.test.ts
  harness/helpers.ts
  proxies/nodejs/entityTypes.ts
  proxies/nodejs/handlers/location.ts
Labels: 10 min review

#60 docs: add OpenAPI spec
  .gitignore
  docs/README.md
  docs/spec.yaml
  docs/widdershins/README.md
  docs/widdershins/options.json
  docs/widdershins/templates/authentication.def
  docs/widdershins/templates/authentication_none.def
  docs/widdershins/templates/callbacks.def
  docs/widdershins/templates/debug.def
  docs/widdershins/templates/discovery.def
  docs/widdershins/templates/footer.def
  docs/widdershins/templates/links.def
  docs/widdershins/templates/main.dot
  docs/widdershins/templates/operation.dot
  docs/widdershins/templates/parameters.def
  docs/widdershins/templates/responses.def
  docs/widdershins/templates/security.def
  docs/widdershins/templates/translations.dot
  proxies/nodejs/handlers/client.ts
Labels: 30 min review

#51 handle commands endpoint python
  harness/types/sdks.ts
  proxies/python/__init__.py
  proxies/python/app.py
  proxies/python/handlers/__init__.py
  proxies/python/handlers/client.py
  proxies/python/handlers/command.py
  proxies/python/handlers/user.py
  proxies/python/helpers/__init__.py
  proxies/python/helpers/camelcase.py
  proxies/python/helpers/entity_types.py
Labels: 20 min review

#65 [DVC-5474] fix: throw missing entity error through params
  harness/features/variable.cloud.test.ts
  proxies/nodejs/handlers/location.ts
Labels: 1 min review

#67 expect commands to succeed by default unless expected to fail
  harness/features/allFeatures.cloud.test.ts
  harness/features/allFeatures.local.test.ts
  harness/features/allVariables.cloud.test.ts
  harness/features/allVariables.local.test.ts
  harness/features/initialize.cloud.test.ts
  harness/features/initialize.local.test.ts
  harness/features/variable.cloud.test.ts
  harness/features/variable.local.test.ts
  harness/helpers.ts
Labels: 10 min review

#64 DVC-5431 client endpoint dotnet
  proxies/dotnet/Controllers/Client.cs
  proxies/dotnet/Dockerfile
  proxies/dotnet/Program.cs
  proxies/dotnet/dotnet.csproj
Labels: 10 min review

#63 feat: user endpoint dotnet
  .gitignore
  proxies/dotnet/Controllers/User.cs
  proxies/dotnet/Models/ClientRequestUser.cs
Labels: 10 min review

#69 move enableCloudBucketing option out of SDK options
  harness/features/initialize.local.test.ts
  harness/helpers.ts
  proxies/nodejs/entityTypes.ts
  proxies/nodejs/handlers/client.ts
Labels: 5 min review

#70 add client endpoint for java proxy
  proxies/java/build.gradle
  proxies/java/src/main/java/com/dvc_harness/proxy/controller/ProxyController.java
  proxies/java/src/main/java/com/dvc_harness/proxy/data/DataStore.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/ClientOptions.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/ClientRequestBody.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/MessageResponse.java
Labels: 10 min review

#71 remove age field from user objects used in tests
  harness/features/allVariables.cloud.test.ts
  harness/features/allVariables.local.test.ts
Labels: 1 min review, safe-changes

#72 expect user request to succeed by default
  harness/helpers.ts
Labels: 5 min review

#73 fix some python proxy issues that allow more tests to pass
  harness/features/variable.local.test.ts
  proxies/python/app.py
  proxies/python/handlers/command.py
  proxies/python/handlers/user.py
  proxies/python/helpers/camelcase.py
  proxies/python/helpers/to_dict.py
Labels: 10 min review

#74 java client error handling
  proxies/java/src/main/java/com/dvc_harness/proxy/controller/ProxyController.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/AsyncErrorResponse.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/BaseResponse.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/ExceptionResponse.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/MessageResponse.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/Spec.java
Labels: 10 min review

#75 Dvc 5462 user endpoint
  proxies/java/src/main/java/com/dvc_harness/proxy/controller/ProxyController.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/UserData.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/UserRequestBody.java
Labels: 5 min review

#77 expect variable type field in harness tests
  harness/features/variable.cloud.test.ts
  harness/features/variable.local.test.ts
Labels: 5 min review, safe-changes

#79 fix variable type test
  harness/features/variable.local.test.ts
Labels: 1 min review, safe-changes

#80 DVC-5572 nock reset scopes
  harness/features/variable.local.test.ts
  harness/helpers.ts
  harness/nock.ts
Labels: 5 min review

#78 feat: install dotnet local package if github sha is present
  docker-compose.yml
  proxies/dotnet/Dockerfile
  proxies/dotnet/install.sh
  proxies/nodejs/install.sh
Labels: 5 min review

#81 DVC-5558 user creation tests
  harness/features/allFeatures.cloud.test.ts
  harness/features/allFeatures.local.test.ts
  harness/features/allVariables.cloud.test.ts
  harness/features/allVariables.local.test.ts
  harness/features/initialize.cloud.test.ts
  harness/features/initialize.local.test.ts
  harness/features/track.cloud.test.ts
  harness/features/track.local.test.ts
  harness/features/variable.cloud.test.ts
  harness/features/variable.local.test.ts
  harness/helpers.ts
  proxies/nodejs/handlers/user.ts
  proxies/nodejs/package.json
  proxies/nodejs/yarn.lock
Labels: 30 min review

#83 Split base URL override to match new changes
  harness/helpers.ts
  proxies/dotnet/.gitignore
  proxies/dotnet/Controllers/Client.cs
  proxies/dotnet/Controllers/HelloWorld.cs
  proxies/dotnet/Controllers/Spec.cs
  proxies/dotnet/Controllers/User.cs
  proxies/dotnet/DataStore.cs
  proxies/dotnet/Program.cs
Labels: 10 min review

#85 fix user endpoint response
  proxies/dotnet/Controllers/User.cs
Labels: 1 min review

#84 chore: change location endpoint usage
  harness/features/allFeatures.cloud.test.ts
  harness/features/allFeatures.local.test.ts
  harness/features/allVariables.cloud.test.ts
  harness/features/allVariables.local.test.ts
  harness/features/track.cloud.test.ts
  harness/features/track.local.test.ts
  harness/features/variable.cloud.test.ts
  harness/features/variable.local.test.ts
  harness/helpers.ts
Labels: 30 min review

#86 Dvc 5433 dotnet location
  harness/types/sdks.ts
  proxies/dotnet/Controllers/Location.cs
  proxies/dotnet/Controllers/User.cs
  proxies/dotnet/Models/ClientRequestUser.cs
  proxies/dotnet/Program.cs
  proxies/dotnet/dotnet.csproj
Labels: 20 min review

#87 add ability to wait for client initialized
  proxies/nodejs/handlers/client.ts
Labels: 1 min review

#89 Update location endpoint to new format c#
  proxies/dotnet/Controllers/Location.cs
  proxies/dotnet/Controllers/User.cs
  proxies/dotnet/DataStore.cs
  proxies/dotnet/Models/ClientRequestEvent.cs
Labels: 10 min review

#88 change harness tests to wait for initialization
  harness/features/allFeatures.local.test.ts
  harness/features/allVariables.local.test.ts
  harness/features/initialize.local.test.ts
  harness/features/track.local.test.ts
  harness/features/variable.local.test.ts
  harness/helpers.ts
Labels: 10 min review

#90 fix: optionally pass initialize callback when creating client
  proxies/dotnet/Controllers/Client.cs
Labels: 5 min review

#92 fix client endpoint options parsing
  proxies/dotnet/Controllers/Client.cs
Labels: 1 min review

#93 skip close method
  proxies/dotnet/Controllers/Location.cs
Labels: 1 min review

#91 chore: added helper for comparing exception messages
  harness/features/allFeatures.local.test.ts
  harness/features/initialize.cloud.test.ts
  harness/features/initialize.local.test.ts
  harness/features/track.cloud.test.ts
  harness/features/track.local.test.ts
  harness/features/variable.cloud.test.ts
  harness/helpers.ts
Labels: 5 min review

#95 fix number params parsing for integers
  proxies/dotnet/Controllers/Location.cs
Labels: 1 min review

#96 fix event flush override option on c#
  proxies/dotnet/Controllers/Client.cs
Labels: 1 min review

#97 change event type and platform assertion
  harness/features/variable.local.test.ts
Labels: 1 min review, safe-changes

#98 fix event flush interval override and numberic casting
  proxies/dotnet/Controllers/Client.cs
  proxies/dotnet/Controllers/Location.cs
Labels: 1 min review

#99 remove platform assertion from cloud event
  harness/features/track.local.test.ts
Labels: 1 min review, safe-changes
