Repository DevCycleHQ/test-harness, pull requests merged in 2023-05, with the labels that each got.

#237 Add clientCustomData to dotnet SDK tests
  harness/types/capabilities.ts
  proxies/dotnet/Controllers/Location.cs
Labels: 1 min review

#117 use jest projects to run sdk tests in parallel
  docs/GUIDE.MD
  harness/features/allFeatures.cloud.test.ts
  harness/features/allFeatures.local.test.ts
  harness/features/allVariables.cloud.test.ts
  harness/features/allVariables.local.test.ts
  harness/features/clientCustomData.test.ts
  harness/features/initialize.cloud.test.ts
  harness/features/initialize.local.test.ts
  harness/features/multithreading.local.test.ts
  harness/features/track.cloud.test.ts
  harness/features/track.local.test.ts
  harness/features/variable.cloud.test.ts
  harness/features/variable.local.test.ts
  harness/helpers.ts
  harness/types/sdks.ts
  jest-global.ts
  jest-setup.js
  jest-testcontainers-config.js
  jest.config.ts
Labels: 20 min review

#248 DVC-7319 adding variableValue tests
  docs/LOCAL.md
  harness/features/variable.cloud.test.ts
  harness/features/variable.local.test.ts
  harness/helpers.ts
  harness/types/capabilities.ts
  jest.config.ts
  package.json
  proxies/dotnet/Controllers/Location.cs
  proxies/go/app.go
  proxies/go/handler_command.go
  proxies/nodejs/handlers/client.ts
  proxies/nodejs/yarn.lock
  proxies/openfeature-nodejs/handlers/location.ts
  proxies/ruby/app.rb
Labels: 5 min review

#250 DVC 7423: Update to test default native bucketing in Go SDK
  docker-compose.yml
  harness/features/multithreading.local.test.ts
  harness/helpers.ts
  harness/types/capabilities.ts
  harness/types/sdks.ts
  jest.config.ts
Labels: 1 min review

#249 PHP Test Harness - Proxy mode
  action.yml
  docker-compose.yml
  docs/LOCAL.md
  harness/features/variable.local.test.ts
  harness/helpers.ts
  harness/types/capabilities.ts
  harness/types/sdks.ts
  jest.config.ts
  proxies/php/Dockerfile
  proxies/php/configs/fpm-pool.conf
  proxies/php/configs/nginx.conf
  proxies/php/configs/php.ini
  proxies/php/configs/supervisord.conf
  proxies/php/nginx/nginx.conf
  proxies/php/php-proxy/.gitignore
  proxies/php/php-proxy/composer.json
  proxies/php/php-proxy/composer.lock
  proxies/php/php-proxy/index.php
  proxies/php/php-proxy/install.sh
  proxies/php/sidecar-manager/go.mod
  proxies/php/sidecar-manager/go.sum
  proxies/php/sidecar-manager/main.go
  proxies/php/startup.sh
Labels: 30 min review

#251 upgrade to use local-bucketing-proxy v1.0.0
  proxies/php/sidecar-manager/go.mod
  proxies/php/sidecar-manager/go.sum
  proxies/php/sidecar-manager/main.go
Labels: 1 min review
