Repository DevCycleHQ/test-harness, pull requests merged in 2023-01, with the labels that each got.

#101 fix: initialize tests
  harness/features/initialize.local.test.ts
  proxies/dotnet/Controllers/Client.cs
Labels: 1 min review

#100 fix proxy error handling
  proxies/dotnet/Controllers/Location.cs
Labels: 1 min review

#102 Test user platform on event tests
  harness/features/track.cloud.test.ts
  harness/features/track.local.test.ts
  harness/features/variable.local.test.ts
  harness/helpers.ts
Labels: 10 min review

#103 call dispose when close is called for C#
  proxies/dotnet/Controllers/Location.cs
Labels: 1 min review

#104 null check await call
  proxies/dotnet/Controllers/Location.cs
Labels: 1 min review

#105 remove close call on invalid client tests
  harness/features/initialize.local.test.ts
Labels: 1 min review, safe-changes

#106 update track call for cloud client to wait for track
  harness/features/track.cloud.test.ts
  harness/helpers.ts
Labels: 1 min review

#107 fix proxy location endpoint await logic
  proxies/dotnet/Controllers/Location.cs
Labels: 1 min review

#109 handle null value jtoken
  proxies/dotnet/Controllers/Location.cs
Labels: 1 min review

#110 Delete client on close
  proxies/dotnet/Controllers/Location.cs
Labels: 1 min review

#112 fix dotnet dockerfile to run install script
  proxies/dotnet/Dockerfile
  proxies/dotnet/dotnet.csproj
Labels: 1 min review

#114 Fix variable local ordering
  harness/features/variable.local.test.ts
Labels: 1 min review, safe-changes

#115 change default jest timeout to 60 seconds
  harness/features/allFeatures.cloud.test.ts
  harness/features/allFeatures.local.test.ts
  harness/features/allVariables.cloud.test.ts
  harness/features/allVariables.local.test.ts
  harness/features/initialize.cloud.test.ts
  harness/features/initialize.local.test.ts
  harness/features/track.cloud.test.ts
  harness/features/track.local.test.ts
  harness/features/variable.cloud.test.ts
  harness/features/variable.local.test.ts
  jest.config.js
Labels: 5 min review

#111 enable the dotnet tests and make the test run not required
  docker-compose.yml
  harness/types/sdks.ts
Labels: 5 min review

#116 remove nock restore after each sdk test suite
  harness/helpers.ts
Labels: 1 min review

#118 log warning when expected error message does not match
  harness/helpers.ts
Labels: 1 min review

#119 fix checking out the dotnet SDK from github SHA
  proxies/dotnet/Dockerfile
  proxies/dotnet/install.sh
Labels: 5 min review

#120 fix github sha install on dotnet
  proxies/dotnet/install.sh
Labels: 1 min review

#123 update the spec to match the new proxy endpoint behaviour
  docs/README.md
  docs/spec.yaml
  proxies/dotnet/Controllers/HelloWorld.cs
  proxies/nodejs/handlers/user.ts
Labels: 30 min review

#125 remove handleUser usage
  proxies/nodejs/app.ts
Labels: 1 min review

#124 chore: added a guide.md to prescribe how to write test harness tests
  docs/GUIDE.MD
  harness/features/variable.cloud.test.ts
  harness/features/variable.local.test.ts
Labels: 10 min review

#126 add readme for running the test harness against local sdks
  README.md
  harness/features/allFeatures.cloud.test.ts
  harness/features/variable.local.test.ts
Labels: 1 min review

#128 remove createUser method from helpers and clean up imports
  harness/features/allFeatures.cloud.test.ts
  harness/features/allVariables.cloud.test.ts
  harness/features/allVariables.local.test.ts
  harness/features/initialize.cloud.test.ts
  harness/features/track.cloud.test.ts
  harness/features/track.local.test.ts
  harness/helpers.ts
Labels: 5 min review

#129 remove users from datastore for node proxy
  proxies/nodejs/app.ts
  proxies/nodejs/entityTypes.ts
  proxies/nodejs/handlers/location.ts
Labels: 1 min review

#127 Fix allVariables failure case test
  harness/features/allVariables.cloud.test.ts
Labels: 1 min review, safe-changes

#130 Set run name to PR title on github workflow
  .github/workflows/config.yml
Labels: 1 min review

#132 Add title to workflow inputs
  .github/workflows/config.yml
Labels: 1 min review

#133 Add go proxy with /spec and /helloworld
  proxies/go/app.go
Labels: 5 min review

#135 install from github sha for Go proxy
  docker-compose.yml
  proxies/go/Dockerfile
  proxies/go/install.sh
Labels: 5 min review

#136 add json parsing for command endpoint
  proxies/go/app.go
  proxies/go/go.mod
  proxies/go/go.sum
  proxies/go/handler_command.go
Labels: 10 min review

#138 Add datastore to go proxy
  proxies/go/app.go
Labels: 1 min review

#137 more Go JSON parsing, handle unknown value field and optionals
  proxies/go/app.go
  proxies/go/handler_command.go
Labels: 1 min review

#142 Add Go SDK to list of SDKs to test
  harness/types/capabilities.ts
  harness/types/sdks.ts
Labels: 1 min review

#143 update options so url overrides work
  proxies/go/handler_client.go
Labels: 1 min review

#140 Add location endpoint to go proxy
  proxies/go/app.go
  proxies/go/handler_client.go
  proxies/go/handler_command.go
Labels: 30 min review

#144 remove spaces
  proxies/go/handler_client.go
Labels: 1 min review

#146 fix go proxy install.sh
  proxies/go/install.sh
Labels: 1 min review

#145 update Go proxy to accommodate the rename changes in the SDK
  proxies/go/handler_client.go
  proxies/go/handler_command.go
Labels: 1 min review

#147 add LOCAL_MODE env var to set local URLs properly
  README.md
  harness/helpers.ts
Labels: 1 min review

#148 Use new DVCOptions in go proxy
  proxies/go/handler_client.go
  proxies/go/handler_command.go
Labels: 5 min review

#151 fix sending location header on go proxy
  proxies/go/handler_client.go
  proxies/go/handler_command.go
Labels: 1 min review

#153 Add BucketingAPIURI override and parse empty map results as {} instead of null
  proxies/go/handler_client.go
  proxies/go/handler_command.go
Labels: 5 min review

#155 fix command endpoint storing results and close method
  proxies/go/handler_command.go
Labels: 1 min review

#156 Java proxy: Remove /user endpoint
  package.json
  proxies/java/src/main/java/com/dvc_harness/proxy/controller/ProxyController.java
Labels: 1 min review

#154 Dvc 5860 - Use ReadOnlyVariable for allVariables in go proxy
  proxies/go/handler_command.go
Labels: 1 min review

#157 add waitForInitialization functionality to proxy server
  proxies/go/handler_client.go
Labels: 1 min review

#158 fix serializing variable responses on go
  proxies/go/handler_command.go
Labels: 1 min review

#159 exact match the variable data for local variable test
  harness/features/variable.local.test.ts
Labels: 1 min review, safe-changes

#160 remove auth
  proxies/go/app.go
  proxies/go/handler_client.go
  proxies/go/handler_command.go
Labels: 1 min review

#161 Handle request errors in go proxy
  proxies/go/handler_command.go
Labels: 1 min review

#162 fix: check if result has more than one item in its array
  proxies/go/handler_command.go
Labels: 1 min review

#163 remove usage of DevCycleApi from go proxy
  proxies/go/handler_command.go
Labels: 1 min review

#164 fix client instance references
  proxies/go/app.go
  proxies/go/handler_client.go
  proxies/go/handler_command.go
Labels: 1 min review

#165 fix variable local tests timing
  harness/features/allVariables.local.test.ts
Labels: 1 min review, safe-changes

#167 fix allfeatures flake
  harness/features/allFeatures.local.test.ts
Labels: 1 min review, safe-changes

#166 go v2 package
  proxies/go/app.go
  proxies/go/go.mod
  proxies/go/go.sum
  proxies/go/handler_client.go
  proxies/go/handler_command.go
  proxies/go/install.sh
Labels: 30 min review

#108 test config fetching with etag and failure behaviour
  harness/features/initialize.local.test.ts
  harness/mockData/index.ts
  harness/mockData/users.ts
Labels: 5 min review

#170 [chore] change the java proxy to amd64 base images to run and test locally
  docker-compose.yml
  harness/types/sdks.ts
  proxies/java/Dockerfile
Labels: 5 min review

#168 fix handling nil values in params for go
  proxies/go/handler_command.go
Labels: 1 min review

#171 add test for stopping polling interval on 403 error
  harness/features/initialize.local.test.ts
Labels: 1 min review, safe-changes

#172 test receiving invalid data from valid json
  harness/features/initialize.local.test.ts
Labels: 1 min review, safe-changes

#169 [feat] Implement location endpoint
  proxies/java/src/main/java/com/dvc_harness/proxy/controller/ProxyController.java
  proxies/java/src/main/java/com/dvc_harness/proxy/data/DataStore.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/CommandResult.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/EntityTypes.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/ExceptionResponse.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/LocationParam.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/LocationParamType.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/LocationRequestBody.java
  proxies/java/src/main/java/com/dvc_harness/proxy/models/LocationResponse.java
Labels: 20 min review

#174 [fix] Java: Get correct entity type
  proxies/java/src/main/java/com/dvc_harness/proxy/models/CommandResult.java
Labels: 1 min review

#176 fix shouldFail check to fail if it succeeds unexpectedly
  harness/helpers.ts
Labels: 5 min review

#180 Dvc 5965 set minimum node version for test harness
  package.json
Labels: 1 min review, 20 min review

#179 Expect exception thrown on initialize if 4xx level error
  harness/features/initialize.local.test.ts
  proxies/dotnet/Controllers/Client.cs
Labels: 5 min review

#178 add tests for invalid sdk key to cloud suites
  harness/features/allFeatures.cloud.test.ts
  harness/features/track.cloud.test.ts
  harness/features/variable.cloud.test.ts
Labels: 5 min review, safe-changes
