Repository DevCycleHQ/test-harness, pull requests merged in 2023-10, with the labels that each got.

#277 chore: Fix PHP sidecar dependabot alerts
  proxies/php/sidecar-manager/go.mod
  proxies/php/sidecar-manager/go.sum
Labels: 1 min review

#278 chore: dependabot
  .github/dependabot.yml
Labels: 5 min review

#306 fix: All .NET functions are async now; and need to be awaited.
  proxies/dotnet/Controllers/Location.cs
  proxies/dotnet/dotnet.csproj
Labels: 10 min review
