Repository DevCycleHQ/test-harness, pull requests merged in 2023-02, with the labels that each got.

#183 DVC-6012 skip failing nodeJS test
  harness/features/initialize.local.test.ts
  yarn.lock
Labels: 1 min review, safe-changes

#185 DVC-6142 client custom data tests
  harness/features/clientCustomData.test.ts
  harness/helpers.ts
  harness/types/capabilities.ts
  proxies/go/handler_command.go
Labels: 5 min review

#186 chore: change allFeatures uninitialized client mock to return a 500
  harness/features/allFeatures.local.test.ts
Labels: 5 min review, safe-changes

#188 DVC-6222 fix initialize SDK tests with new expectErrorToContain()
  harness/features/initialize.local.test.ts
Labels: 5 min review, safe-changes

#190 strengthen variable event tests to check for every field
  harness/features/variable.local.test.ts
  jest-setup.js
  jest.config.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: 5 min review

#192 allow empty date field, and others
  harness/features/variable.local.test.ts
Labels: 5 min review, safe-changes

#195 track unmatched scopes and log the test case name that caused them
  harness/features/allFeatures.cloud.test.ts
  harness/features/allFeatures.local.test.ts
  harness/features/allVariables.cloud.test.ts
  harness/features/allVariables.local.test.ts
  harness/features/clientCustomData.test.ts
  harness/features/initialize.local.test.ts
  harness/features/track.cloud.test.ts
  harness/features/track.local.test.ts
  harness/features/variable.cloud.test.ts
  harness/features/variable.local.test.ts
  harness/helpers.ts
  harness/mockServer/index.ts
Labels: 5 min review

#196 write docs for how to run test harness and move local run instructions
  README.md
  docs/LOCAL.md
Labels: 1 min review, safe-changes

#193 update track event tests to track exact fields
  harness/features/track.local.test.ts
  harness/features/variable.local.test.ts
  harness/mockData/events.ts
Labels: 5 min review

#199 add /spec endpoint for ruby proxy
  proxies/ruby/app.rb
Labels: 1 min review

#200 DVC-6336 - Dockerize Ruby
  proxies/ruby/Dockerfile
  proxies/ruby/Gemfile
  proxies/ruby/install.sh
Labels: 1 min review

#201 add /client endpoint for Ruby proxy
  proxies/ruby/Gemfile.lock
  proxies/ruby/app.rb
Labels: 5 min review

#202 test for uninitialized event sending
  harness/features/variable.local.test.ts
Labels: 5 min review, safe-changes

#203 upgrade to yarn3
  .gitignore
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  package.json
  proxies/nodejs/.yarn/releases/yarn-3.4.1.cjs
  proxies/nodejs/.yarnrc.yml
  proxies/nodejs/package.json
  proxies/nodejs/yarn.lock
  yarn.lock
Labels: 5 min review

#204 update nodejs docs to use portals
  docs/LOCAL.md
  package.json
Labels: 1 min review

#205 expect two attempts on uninitialzed due to failure test
  harness/features/variable.local.test.ts
Labels: 1 min review, safe-changes

#207 update go local instructions to use v2 package
  docs/LOCAL.md
Labels: 1 min review, safe-changes

#206 Add action to be triggered from other SDK repos.
  action.yml
  docker-compose.yml
Labels: 5 min review

#208 fix client custom data test to expect event to be sent
  harness/features/clientCustomData.test.ts
Labels: 1 min review, safe-changes
