Repository DevCycleHQ/test-harness, pull requests merged in 2023-03, with the labels that each got.

#209 Disable ruby proxy.
  docker-compose.yml
Labels: 5 min review

#210 DVC-6335 - Add ruby to SDK's and capabilities.
  harness/types/capabilities.ts
  harness/types/sdks.ts
Labels: 1 min review

#211 checkout fetch depth to be all history instead of a shallow checkout.
  action.yml
Labels: 1 min review

#215 fix: correctly link local packages in node install script
  proxies/nodejs/install.sh
Labels: 1 min review

#212 add script to check out local configuration automatically
  README.md
  package.json
  scripts/use-local.sh
Labels: 1 min review

#213 add /command endpoint for Ruby proxy
  proxies/ruby/app.rb
  proxies/ruby/helpers.rb
  proxies/ruby/utils.rb
Labels: 10 min review

#216 chore: add Ruby local instructions to LOCAL.md
  docs/LOCAL.md
Labels: 1 min review

#219 fix: return exception in body instead of error
  proxies/ruby/app.rb
Labels: 1 min review

#218 fix: change test to send type instead of just target
  harness/features/track.cloud.test.ts
Labels: 1 min review, safe-changes

#222 install protoc in nodejs dockerfile
  proxies/nodejs/Dockerfile
Labels: 1 min review

#217 DVC-6514 Adding yarn build:docker step to build docker images using depot.dev
  .github/workflows/config.yml
  action.yml
  package.json
Labels: 5 min review

#224 chore: enable ruby sdk
  docker-compose.yml
  harness/types/sdks.ts
  proxies/ruby/Dockerfile
  proxies/ruby/config.ru
  proxies/ruby/install.sh
  proxies/ruby/puma.rb
Labels: 5 min review

#226 fix: invalid user in clientCustomData test
  harness/features/clientCustomData.test.ts
Labels: 1 min review, safe-changes

#227 add multithreading test for setting client custom data
  harness/features/multithreading.local.test.ts
Labels: 5 min review, safe-changes

#230 fix: for NodeJS, add expect.toBeNil() for evalReason
  harness/features/variable.local.test.ts
Labels: 5 min review, safe-changes

#231 chore: add a variable test for unicode characters
  harness/features/variable.local.test.ts
  harness/mockData/config.ts
  harness/mockData/variables.ts
Labels: 5 min review

#234 Show jest test results nicely in Github
  .github/workflows/config.yml
  .gitignore
  action.yml
  package.json
  yarn.lock
Labels: 5 min review
