Repository DevCycleHQ/test-harness, pull requests merged in 2024-05, with the labels that each got.

#422 chore: update yarn to 4.1.1
  .yarn/releases/yarn-3.4.1.cjs
  .yarn/releases/yarn-4.1.1.cjs
  .yarnrc.yml
  package.json
  proxies/nodejs/.yarn/releases/yarn-3.4.1.cjs
  proxies/nodejs/.yarn/releases/yarn-4.1.1.cjs
  proxies/nodejs/.yarnrc.yml
  proxies/nodejs/install.sh
  proxies/nodejs/package.json
  proxies/nodejs/yarn.lock
  proxies/openfeature-nodejs/.yarn/releases/yarn-3.4.1.cjs
  proxies/openfeature-nodejs/.yarn/releases/yarn-4.1.1.cjs
  proxies/openfeature-nodejs/.yarnrc.yml
  proxies/openfeature-nodejs/Dockerfile
  proxies/openfeature-nodejs/install.sh
  proxies/openfeature-nodejs/package.json
  proxies/openfeature-nodejs/yarn.lock
  yarn.lock
Labels: 5 min review

#421 chore: add Last-Modified header support for CDN configs
  harness/features/initialize.local.test.ts
  harness/features/multithreading.local.test.ts
  harness/features/variable.local.test.ts
  harness/helpers/events.ts
  harness/types/capabilities.ts
  proxies/go/go.mod
  proxies/go/go.sum
  proxies/openfeature-nodejs/package.json
  proxies/openfeature-nodejs/yarn.lock
Labels: 5 min review

#426 add bootstrapping tests
  docs/LOCAL.md
  harness/features/__snapshots__/bootstrapping.test.ts.snap
  harness/features/bootstrapping.test.ts
  harness/helpers/commands.ts
  harness/helpers/helpers.ts
  harness/helpers/index.ts
  harness/types/capabilities.ts
  package.json
  proxies/nodejs/install.sh
  proxies/nodejs/package.json
  proxies/nodejs/yarn.lock
  yarn.lock
Labels: 5 min review

#427 add sdk key to bootstrapped config
  harness/features/__snapshots__/bootstrapping.test.ts.snap
  harness/features/bootstrapping.test.ts
Labels: 1 min review, safe-changes

#428 remove snapshot test
  harness/features/__snapshots__/bootstrapping.test.ts.snap
  harness/features/bootstrapping.test.ts
Labels: 1 min review

#429 rename to client sdk key
  harness/features/bootstrapping.test.ts
Labels: 1 min review, safe-changes
