Repository DevCycleHQ/test-harness, pull requests merged in 2024-04, with the labels that each got.

#401 fix: global.fetch failure on tests
  harness/helpers.ts
Labels: 1 min review

#402 chore: dependabot security updates
  yarn.lock
Labels: 1 min review

#405 update test harness to expect variable default reason when SDK is capable
  harness/features/multithreading.local.test.ts
  harness/features/variable.local.test.ts
  harness/helpers/events.ts
  harness/helpers/helpers.ts
  harness/helpers/index.ts
  harness/types/capabilities.ts
  jest-global.ts
  jest.config.ts
Labels: 5 min review

#408 fix expected default reasons
  harness/features/multithreading.local.test.ts
  harness/features/variable.local.test.ts
Labels: 1 min review, safe-changes

#409 Test for etag metadata
  harness/features/multithreading.local.test.ts
  harness/features/variable.local.test.ts
  harness/helpers/events.ts
  harness/types/capabilities.ts
Labels: 5 min review

#410 add test for config etag caching and reporting
  harness/features/initialize.local.test.ts
  harness/features/variable.local.test.ts
  harness/helpers/events.ts
  harness/mockServer/index.ts
Labels: 5 min review

#414 Rayid tracking
  harness/features/initialize.local.test.ts
  harness/features/variable.local.test.ts
  harness/helpers/events.ts
Labels: 1 min review

#415 update multithreading tests with rayid
  harness/features/multithreading.local.test.ts
Labels: 1 min review, safe-changes

#418 Change dependabot to weekly
  .github/dependabot.yml
Labels: 1 min review

#419 chore: update OpenFeature packages
  proxies/nodejs/package.json
  proxies/nodejs/yarn.lock
  proxies/openfeature-nodejs/package.json
  proxies/openfeature-nodejs/yarn.lock
Labels: 1 min review

#420 Disable SSE during test harness until we write functionality for it.
  proxies/go/Dockerfile
  proxies/go/app.go
  proxies/go/go.mod
  proxies/go/go.sum
  proxies/go/handler_client.go
  proxies/go/handler_command.go
Labels: 1 min review

#424 Comment out SSE - as SSE didn't end up getting merged
  proxies/go/handler_client.go
Labels: 1 min review
